/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/components/DeepDemo': RouteRecordInfo<'/components/DeepDemo', '/components/DeepDemo', Record<never, never>, Record<never, never>>,
    '/components/StuDemoSon4': RouteRecordInfo<'/components/StuDemoSon4', '/components/StuDemoSon4', Record<never, never>, Record<never, never>>,
    '/StuDemo1': RouteRecordInfo<'/StuDemo1', '/StuDemo1', Record<never, never>, Record<never, never>>,
    '/StuDemo10': RouteRecordInfo<'/StuDemo10', '/StuDemo10', Record<never, never>, Record<never, never>>,
    '/StuDemo11': RouteRecordInfo<'/StuDemo11', '/StuDemo11', Record<never, never>, Record<never, never>>,
    '/StuDemo12': RouteRecordInfo<'/StuDemo12', '/StuDemo12', Record<never, never>, Record<never, never>>,
    '/StuDemo13': RouteRecordInfo<'/StuDemo13', '/StuDemo13', Record<never, never>, Record<never, never>>,
    '/StuDemo14': RouteRecordInfo<'/StuDemo14', '/StuDemo14', Record<never, never>, Record<never, never>>,
    '/StuDemo15': RouteRecordInfo<'/StuDemo15', '/StuDemo15', Record<never, never>, Record<never, never>>,
    '/StuDemo16': RouteRecordInfo<'/StuDemo16', '/StuDemo16', Record<never, never>, Record<never, never>>,
    '/StuDemo17': RouteRecordInfo<'/StuDemo17', '/StuDemo17', Record<never, never>, Record<never, never>>,
    '/StuDemo18': RouteRecordInfo<'/StuDemo18', '/StuDemo18', Record<never, never>, Record<never, never>>,
    '/StuDemo19': RouteRecordInfo<'/StuDemo19', '/StuDemo19', Record<never, never>, Record<never, never>>,
    '/StuDemo2': RouteRecordInfo<'/StuDemo2', '/StuDemo2', Record<never, never>, Record<never, never>>,
    '/StuDemo20': RouteRecordInfo<'/StuDemo20', '/StuDemo20', Record<never, never>, Record<never, never>>,
    '/StuDemo21': RouteRecordInfo<'/StuDemo21', '/StuDemo21', Record<never, never>, Record<never, never>>,
    '/StuDemo22': RouteRecordInfo<'/StuDemo22', '/StuDemo22', Record<never, never>, Record<never, never>>,
    '/StuDemo23': RouteRecordInfo<'/StuDemo23', '/StuDemo23', Record<never, never>, Record<never, never>>,
    '/StuDemo24': RouteRecordInfo<'/StuDemo24', '/StuDemo24', Record<never, never>, Record<never, never>>,
    '/StuDemo25': RouteRecordInfo<'/StuDemo25', '/StuDemo25', Record<never, never>, Record<never, never>>,
    '/StuDemo26': RouteRecordInfo<'/StuDemo26', '/StuDemo26', Record<never, never>, Record<never, never>>,
    '/StuDemo27': RouteRecordInfo<'/StuDemo27', '/StuDemo27', Record<never, never>, Record<never, never>>,
    '/StuDemo28': RouteRecordInfo<'/StuDemo28', '/StuDemo28', Record<never, never>, Record<never, never>>,
    '/StuDemo29': RouteRecordInfo<'/StuDemo29', '/StuDemo29', Record<never, never>, Record<never, never>>,
    '/StuDemo3': RouteRecordInfo<'/StuDemo3', '/StuDemo3', Record<never, never>, Record<never, never>>,
    '/StuDemo30': RouteRecordInfo<'/StuDemo30', '/StuDemo30', Record<never, never>, Record<never, never>>,
    '/StuDemo31': RouteRecordInfo<'/StuDemo31', '/StuDemo31', Record<never, never>, Record<never, never>>,
    '/StuDemo32': RouteRecordInfo<'/StuDemo32', '/StuDemo32', Record<never, never>, Record<never, never>>,
    '/StuDemo33': RouteRecordInfo<'/StuDemo33', '/StuDemo33', Record<never, never>, Record<never, never>>,
    '/StuDemo34': RouteRecordInfo<'/StuDemo34', '/StuDemo34', Record<never, never>, Record<never, never>>,
    '/StuDemo35': RouteRecordInfo<'/StuDemo35', '/StuDemo35', Record<never, never>, Record<never, never>>,
    '/StuDemo36': RouteRecordInfo<'/StuDemo36', '/StuDemo36', Record<never, never>, Record<never, never>>,
    '/StuDemo4': RouteRecordInfo<'/StuDemo4', '/StuDemo4', Record<never, never>, Record<never, never>>,
    '/StuDemo5': RouteRecordInfo<'/StuDemo5', '/StuDemo5', Record<never, never>, Record<never, never>>,
    '/StuDemo6': RouteRecordInfo<'/StuDemo6', '/StuDemo6', Record<never, never>, Record<never, never>>,
    '/StuDemo7': RouteRecordInfo<'/StuDemo7', '/StuDemo7', Record<never, never>, Record<never, never>>,
    '/StuDemo8': RouteRecordInfo<'/StuDemo8', '/StuDemo8', Record<never, never>, Record<never, never>>,
    '/StuDemo9': RouteRecordInfo<'/StuDemo9', '/StuDemo9', Record<never, never>, Record<never, never>>,
  }
}
