/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/components/DeepDemo': RouteRecordInfo<'/components/DeepDemo', '/components/DeepDemo', Record<never, never>, Record<never, never>>,
    '/StuDemo1': RouteRecordInfo<'/StuDemo1', '/StuDemo1', Record<never, never>, Record<never, never>>,
    '/StuDemo10': RouteRecordInfo<'/StuDemo10', '/StuDemo10', Record<never, never>, Record<never, never>>,
    '/StuDemo11': RouteRecordInfo<'/StuDemo11', '/StuDemo11', Record<never, never>, Record<never, never>>,
    '/StuDemo12': RouteRecordInfo<'/StuDemo12', '/StuDemo12', Record<never, never>, Record<never, never>>,
    '/StuDemo2': RouteRecordInfo<'/StuDemo2', '/StuDemo2', Record<never, never>, Record<never, never>>,
    '/StuDemo3': RouteRecordInfo<'/StuDemo3', '/StuDemo3', Record<never, never>, Record<never, never>>,
    '/StuDemo4': RouteRecordInfo<'/StuDemo4', '/StuDemo4', Record<never, never>, Record<never, never>>,
    '/StuDemo5': RouteRecordInfo<'/StuDemo5', '/StuDemo5', Record<never, never>, Record<never, never>>,
    '/StuDemo6': RouteRecordInfo<'/StuDemo6', '/StuDemo6', Record<never, never>, Record<never, never>>,
    '/StuDemo7': RouteRecordInfo<'/StuDemo7', '/StuDemo7', Record<never, never>, Record<never, never>>,
    '/StuDemo8': RouteRecordInfo<'/StuDemo8', '/StuDemo8', Record<never, never>, Record<never, never>>,
    '/StuDemo9': RouteRecordInfo<'/StuDemo9', '/StuDemo9', Record<never, never>, Record<never, never>>,
  }
}
