/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/components/DeepDemo': RouteRecordInfo<'/components/DeepDemo', '/components/DeepDemo', Record<never, never>, Record<never, never>>,
    '/components/StuDemoSon4': RouteRecordInfo<'/components/StuDemoSon4', '/components/StuDemoSon4', Record<never, never>, Record<never, never>>,
    '/StuDemo1': RouteRecordInfo<'/StuDemo1', '/StuDemo1', Record<never, never>, Record<never, never>>,
    '/StuDemo10': RouteRecordInfo<'/StuDemo10', '/StuDemo10', Record<never, never>, Record<never, never>>,
    '/StuDemo11': RouteRecordInfo<'/StuDemo11', '/StuDemo11', Record<never, never>, Record<never, never>>,
    '/StuDemo12': RouteRecordInfo<'/StuDemo12', '/StuDemo12', Record<never, never>, Record<never, never>>,
    '/StuDemo13': RouteRecordInfo<'/StuDemo13', '/StuDemo13', Record<never, never>, Record<never, never>>,
    '/StuDemo14': RouteRecordInfo<'/StuDemo14', '/StuDemo14', Record<never, never>, Record<never, never>>,
    '/StuDemo15': RouteRecordInfo<'/StuDemo15', '/StuDemo15', Record<never, never>, Record<never, never>>,
    '/StuDemo16': RouteRecordInfo<'/StuDemo16', '/StuDemo16', Record<never, never>, Record<never, never>>,
    '/StuDemo17': RouteRecordInfo<'/StuDemo17', '/StuDemo17', Record<never, never>, Record<never, never>>,
    '/StuDemo18': RouteRecordInfo<'/StuDemo18', '/StuDemo18', Record<never, never>, Record<never, never>>,
    '/StuDemo19': RouteRecordInfo<'/StuDemo19', '/StuDemo19', Record<never, never>, Record<never, never>>,
    '/StuDemo2': RouteRecordInfo<'/StuDemo2', '/StuDemo2', Record<never, never>, Record<never, never>>,
    '/StuDemo20': RouteRecordInfo<'/StuDemo20', '/StuDemo20', Record<never, never>, Record<never, never>>,
    '/StuDemo3': RouteRecordInfo<'/StuDemo3', '/StuDemo3', Record<never, never>, Record<never, never>>,
    '/StuDemo4': RouteRecordInfo<'/StuDemo4', '/StuDemo4', Record<never, never>, Record<never, never>>,
    '/StuDemo5': RouteRecordInfo<'/StuDemo5', '/StuDemo5', Record<never, never>, Record<never, never>>,
    '/StuDemo6': RouteRecordInfo<'/StuDemo6', '/StuDemo6', Record<never, never>, Record<never, never>>,
    '/StuDemo7': RouteRecordInfo<'/StuDemo7', '/StuDemo7', Record<never, never>, Record<never, never>>,
    '/StuDemo8': RouteRecordInfo<'/StuDemo8', '/StuDemo8', Record<never, never>, Record<never, never>>,
    '/StuDemo9': RouteRecordInfo<'/StuDemo9', '/StuDemo9', Record<never, never>, Record<never, never>>,
  }
}
